/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tim.proyektil;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application{
    
     @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("KarirKita");

        Image icon = new Image(getClass().getResourceAsStream("/Picture2.png")); // Replace with your icon file
        primaryStage.getIcons().add(icon);

        // Create an instance of the login layout
        LoginLayout loginLayout = new LoginLayout();
        
        // // Get the main layout from the login layout
        HBox root = loginLayout.getMainLayout();

        // RegisterLayout registerLayout = new RegisterLayout();

        // HBox root = registerLayout.getMainLayout();
        
        Scene scene = new Scene(root, 650, 640);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
    
    public Object getGreeting() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getGreeting'");
    }
    
}
